In [2]:
import numpy as np 
import numpy.random as npr
import pydtmc

In [3]:
matrix = np.array([
    [0,1,0,0,0],
    [0,0,1,0,0],
    [0.004,0.006,0.9,0.065,0.025],
    [0,0,1,0,0],
    [0,0,1,0,0]],np.dtype('d'))
    

In [4]:
def steady_solution(mat: np.ndarray, iterations: int):
    m= mat.copy()
    for i in range(iterations):
        m = (m@m).round(10)
    return m

pi=np.zeros(len(matrix))
pi[0]=1
P_inf = steady_solution(matrix,1000)
pi=pi@P_inf
print(P_inf)
print(pi)
print(pi.sum())

[[0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]
 [0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]
 [0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]
 [0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]
 [0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]]
[0.00362319 0.00905797 0.9057971  0.05887681 0.02264493]
1.0


In [5]:
for i in range(1,len(pi)):
    pi[i] = pi[i]*1/pi[0]
    pass
pi[0] = 1
print(pi)

[  1.           2.5        250.00000041  16.25000003   6.25      ]


In [8]:
chain = pydtmc.MarkovChain(matrix,["Delay","SWAP_IN","CPU","IO1","IO2"])
print(chain)


DISCRETE-TIME MARKOV CHAIN
 SIZE:           5
 RANK:           3
 CLASSES:        1
  > RECURRENT:   1
  > TRANSIENT:   0
 ERGODIC:        YES
  > APERIODIC:   YES
  > IRREDUCIBLE: YES
 ABSORBING:      NO
 REGULAR:        YES
 REVERSIBLE:     NO
 SYMMETRIC:      NO



In [20]:
pt : pydtmc.MarkovChain  = chain.birth_death([0.1,0.1,0.1,0.1,0],[0,0.3,0.3,0.3,0.3])
print()

[[0.    1.    0.    0.    0.   ]
 [0.    0.    1.    0.    0.   ]
 [0.004 0.006 0.9   0.065 0.025]
 [0.    0.    1.    0.    0.   ]
 [0.    0.    1.    0.    0.   ]]
