In [24]:
import numpy as np 
import numpy.random as npr

In [72]:
generator = npr.default_rng(123456789)
def generate_matrix(shape) -> np.array:
    matrix = generator.integers(1,1000,shape).astype(np.double)
    for i in range(len(matrix)):
        sum = 0
        for j in range(len(matrix[i])):
            sum += matrix[i][j]
            pass 
        for j in range(len(matrix[i])):
            matrix[i][j] = matrix[i][j]/sum
            pass
        pass
    return matrix
    

In [75]:
matrix = generate_matrix((3,3))
print(matrix)
print(np.array([i.sum() for i in [np.array(mat2[k]) for k in range(len(matrix))]]))
mat2 = np.zeros(matrix.shape)
for i in range(len(mat2)):
    for j in range(len(mat2[i])):
        sum = 0
        for k in range(len(mat2[i])):
            sum += matrix[i][k] * matrix[k][j]
            pass
        mat2[i][j] = sum
        sum = 0
        pass
    pass

print(mat2)

[[0.33966942 0.39090909 0.26942149]
 [0.53266332 0.38291457 0.08442211]
 [0.62317073 0.32926829 0.04756098]]
[1. 1. 1.]
[[0.49149383 0.37117661 0.13732956]
 [0.43750338 0.38264403 0.1798526 ]
 [0.41669979 0.38534505 0.19795516]]


In [20]:
def birth_death_process(bp,dp,states):
    matrix = np.zeros((states,states))
    matrix[0][0] = -bp
    matrix[0][1] = bp
    matrix[1][0] = dp
    matrix[states - 1][states - 1] = 1-dp
    for i in range(1,states-1):
        matrix[i][i] = -(bp-dp)
        matrix[i][i+1] = bp
        matrix[i+1][i] = dp
        pass
    return matrix

In [21]:
matrix = birth_death_process(0.6,0.4,10)
print(matrix)

[[-0.6  0.6  0.   0.   0.   0.   0.   0.   0.   0. ]
 [ 0.4 -0.2  0.6  0.   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.4 -0.2  0.6  0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.4 -0.2  0.6  0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.4 -0.2  0.6  0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.4 -0.2  0.6  0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.4 -0.2  0.6  0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.4 -0.2  0.6  0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.4 -0.2  0.6]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.4  0.6]]
